"""empty message

Revision ID: 0902b11db5a2
Revises: 0ab3e389b79f
Create Date: 2025-05-15 10:21:35.005436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0902b11db5a2'
down_revision = '0ab3e389b79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoris',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fa_uid', sa.String(length=128), nullable=True),
    sa.Column('bu_name', sa.String(length=128), nullable=False),
    sa.Column('bu_city', sa.String(length=128), nullable=False),
    sa.Column('bu_uid', sa.String(length=128), nullable=False),
    sa.Column('u_uid', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['u_uid'], ['user.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fa_uid')
    )
    op.add_column('historiques', sa.Column('bu_uid', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'bu_uid')
    op.drop_table('favoris')
    # ### end Alembic commands ###
