"""empty message

Revision ID: 0ab3e389b79f
Revises: f7a0727df6aa
Create Date: 2025-05-14 19:44:40.137909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab3e389b79f'
down_revision = 'f7a0727df6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_uid', sa.String(length=128), nullable=True),
    sa.Column('textSearch', sa.String(length=128), nullable=False),
    sa.Column('bu_name', sa.String(length=128), nullable=False),
    sa.Column('bu_city', sa.String(length=128), nullable=False),
    sa.Column('u_uid', sa.String(length=128), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['u_uid'], ['user.u_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historiques')
    # ### end Alembic commands ###
