"""empty message

Revision ID: 35cfa7cfab14
Revises: b99753d70a15
Create Date: 2024-09-19 14:37:22.624213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35cfa7cfab14'
down_revision = 'b99753d70a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_image1', sa.String(length=128), nullable=False))
    op.add_column('business', sa.Column('bu_image2', sa.String(length=128), nullable=False))
    op.drop_column('business', 'bu_pic2')
    op.drop_column('business', 'bu_pic1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_pic1', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('business', sa.Column('bu_pic2', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('business', 'bu_image2')
    op.drop_column('business', 'bu_image1')
    # ### end Alembic commands ###
