"""empty message

Revision ID: 3883b7a6816d
Revises: 56eabfdc1269
Create Date: 2025-07-08 15:02:49.287901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3883b7a6816d'
down_revision = '56eabfdc1269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('phone', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'phone')
    # ### end Alembic commands ###
