"""empty message

Revision ID: 56eabfdc1269
Revises: 769cc93072b9
Create Date: 2025-07-07 19:08:26.584388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56eabfdc1269'
down_revision = '769cc93072b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'all_business_found',
               existing_type=mysql.VARCHAR(length=128),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'all_business_found',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
