"""empty message

Revision ID: 575fba70f0ee
Revises: a467f024d108
Create Date: 2025-08-21 14:18:52.935128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '575fba70f0ee'
down_revision = 'a467f024d108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_website', sa.String(length=128), nullable=True))
    op.alter_column('business', 'bu_description',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('business', 'bu_city',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('business', 'bu_address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('business', 'bu_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_picture', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('business', 'bu_address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('business', 'bu_city',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('business', 'bu_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('business', 'bu_website')
    # ### end Alembic commands ###
