"""empty message

Revision ID: 690a1a60aea8
Revises: 8fb182c50fc6
Create Date: 2025-07-11 15:32:09.513236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '690a1a60aea8'
down_revision = '8fb182c50fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'ca_description',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'ca_description',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
