"""empty message

Revision ID: 69c410302d42
Revises: 48516baffe43
Create Date: 2024-11-26 12:16:02.837185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c410302d42'
down_revision = '48516baffe43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teller', sa.Column('t_status', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teller', 't_status')
    # ### end Alembic commands ###
