"""empty message

Revision ID: 769cc93072b9
Revises: 98e7449fffb1
Create Date: 2025-07-03 20:38:04.466826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769cc93072b9'
down_revision = '98e7449fffb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('textSearch', sa.String(length=128), nullable=False),
    sa.Column('all_business_found', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('commune', sa.String(length=128), nullable=False),
    sa.Column('longitude', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
