"""empty message

Revision ID: 8b22c490d096
Revises: 0902b11db5a2
Create Date: 2025-05-19 13:20:51.697414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b22c490d096'
down_revision = '0902b11db5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoris', sa.Column('fav_status', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favoris', 'fav_status')
    # ### end Alembic commands ###
