"""empty message

Revision ID: 8fb182c50fc6
Revises: 3883b7a6816d
Create Date: 2025-07-11 13:54:28.956505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fb182c50fc6'
down_revision = '3883b7a6816d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_picture', sa.String(length=255), nullable=True))
    op.drop_column('business', 'bu_image1')
    op.drop_column('business', 'bu_image2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_image2', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('business', sa.Column('bu_image1', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('business', 'bu_picture')
    # ### end Alembic commands ###
