"""empty message

Revision ID: 98e7449fffb1
Revises: 
Create Date: 2025-07-02 14:15:33.191462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e7449fffb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('ad_status', sa.Boolean(), nullable=True))
    op.add_column('advertisement', sa.Column('t_uid', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'advertisement', 'teller', ['t_uid'], ['t_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.drop_column('advertisement', 't_uid')
    op.drop_column('advertisement', 'ad_status')
    # ### end Alembic commands ###
