"""empty message

Revision ID: a3abc73298b0
Revises: 
Create Date: 2024-09-18 16:35:48.224510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3abc73298b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bu_name', table_name='business')
    op.drop_column('business', 'bu_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_name', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('bu_name', 'business', ['bu_name'], unique=False)
    # ### end Alembic commands ###
