"""empty message

Revision ID: a467f024d108
Revises: 5423fe28b8f0
Create Date: 2025-07-14 14:00:07.924969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a467f024d108'
down_revision = '5423fe28b8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'bu_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint(None, 'business', ['bu_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    op.alter_column('business', 'bu_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
