"""empty message

Revision ID: b99753d70a15
Revises: a3abc73298b0
Create Date: 2024-09-18 16:36:09.932257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99753d70a15'
down_revision = 'a3abc73298b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_name', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'business', ['bu_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    op.drop_column('business', 'bu_name')
    # ### end Alembic commands ###
