"""empty message

Revision ID: c205edacdfdf
Revises: dd6c52fdb0e0
Create Date: 2024-09-19 17:39:56.938199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c205edacdfdf'
down_revision = 'dd6c52fdb0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('ad_type', sa.String(length=128), nullable=False))
    op.add_column('advertisement', sa.Column('ad_title', sa.String(length=128), nullable=False))
    op.add_column('advertisement', sa.Column('number_broadcasts', sa.String(length=128), nullable=False))
    op.add_column('advertisement', sa.Column('ad_start_date', sa.String(length=128), nullable=False))
    op.add_column('advertisement', sa.Column('ad_end_date', sa.String(length=128), nullable=True))
    op.alter_column('advertisement', 'ad_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('advertisement', 'ad_description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('advertisement', 'ad_address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint(None, 'advertisement', ['ad_uid'])
    op.drop_column('advertisement', 'ad_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('ad_name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'advertisement', type_='unique')
    op.alter_column('advertisement', 'ad_address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('advertisement', 'ad_description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('advertisement', 'ad_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('advertisement', 'ad_end_date')
    op.drop_column('advertisement', 'ad_start_date')
    op.drop_column('advertisement', 'number_broadcasts')
    op.drop_column('advertisement', 'ad_title')
    op.drop_column('advertisement', 'ad_type')
    # ### end Alembic commands ###
