"""empty message

Revision ID: f03acc03ba96
Revises: 690a1a60aea8
Create Date: 2025-07-11 15:34:40.657199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f03acc03ba96'
down_revision = '690a1a60aea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'ca_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint(None, 'categories', ['ca_uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'ca_uid',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
