"""empty message

Revision ID: f7846b37cc17
Revises: 8b22c490d096
Create Date: 2025-05-19 13:48:57.677472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7846b37cc17'
down_revision = '8b22c490d096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favoris', 'fav_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoris', sa.Column('fav_status', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
