"""empty message

Revision ID: f7a0727df6aa
Revises: 576a58d7b86c
Create Date: 2024-11-26 12:38:31.471445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a0727df6aa'
down_revision = '576a58d7b86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('bu_status', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'bu_status')
    # ### end Alembic commands ###
