"""empty message

Revision ID: fcc831f17640
Revises: f7846b37cc17
Create Date: 2025-06-11 13:54:47.911914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcc831f17640'
down_revision = 'f7846b37cc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'bu_name')
    op.drop_column('historiques', 'bu_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('bu_city', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('historiques', sa.Column('bu_name', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
